name: doyel_live
description: "Live Streaming App."
publish_to: 'none'
version: 1.1.6+18

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  # camera: ^0.11.2
  camera: 0.11.0+2
  carousel_slider: ^5.1.1
  connectivity_plus: ^6.1.5
  country_pickers: ^3.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  dio: ^5.9.0
  emojis: ^0.9.9
  flutter_html: ^3.0.0
  file_picker: ^10.3.2
  flutter_spinkit: ^5.2.2
  flutter_windowmanager_plus: ^1.0.1

  firebase_core: ^3.15.2
  # firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  google_sign_in: ^7.1.1
  app_links: ^6.4.0 # Alternative to uni_links
  # livekit_client: 2.3.6
  # livekit_client: ^2.5.0+hotfix.3
  livekit_client: ^2.5.1


  get: ^4.7.2
  headset_connection_event: ^4.0.2
  intl: ^0.20.2
  loading_overlay: ^0.4.3
  marquee: ^2.3.0
  material_design_icons_flutter: ^7.0.7296
  modal_bottom_sheet: ^3.0.0
  new_version_plus: ^0.1.1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.1
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  streaming_shared_preferences: ^2.0.0
  timeago: ^3.7.1
  web_socket_client: ^0.2.1
  permission_handler: ^11.4.0
  audioplayers: ^6.5.1
  android_id: ^0.4.0
  eva_icons_flutter: ^3.1.0
  flutter_local_notifications: ^19.4.1
  google_fonts: ^6.3.3
  animate_do: ^4.2.0

# dependency_overrides: 
#   # flutter_webrtc: 0.12.7
#   # dart_webrtc: 1.4.10
#   # webrtc_interface: 1.2.0
#   camera_android_camerax: 0.6.10+1
#   fading_edge_scrollview: 4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/others/
